# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0
server:
  env: "development"
  port: 8080

roc:
  base: "http://localhost:8181"
  target: "connectivity-service-v2"
  token: ""

prometheus:
  acc: "http://localhost:9090"
